version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - db.env
    networks:
      - go-todo-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql go-todo-db --password=my-secret-pw --port=3306"
        ]
      interval: 30s
      retries: 5
      timeout: 20s
      start_period: 1m
  gotodomysql:
    image: go-todo-mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - go-todo-network
    depends_on:
      mysql_db:
        condition: "service_healthy"
networks:
  go-todo-network:
    name: go-todo-network
